import type { NextPage } from 'next';
import styled from 'styled-components';
import Head from 'next/head';

const Text = styled.span`
	font-size: 32px;
`;

const Home: NextPage = () => {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Text>Hello world</Text>
		</div>
	);
};

export default Home;
